resources:
  - name: github_new
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
  - name: jfrogFEFS_cp
    type: FileSpec
    configuration:
      sourceArtifactory: entArt
      pattern: "libs-releases-local/com/jfrog/platform/jfrog-frontend-bin/1.*/jfrog-frontend-bin-1.*-*.*"
      recursive: false
      limit: 3
      sortBy:
        - created
      sortOrder: "desc"

pipelines:
  - name: pipeline_new
    steps:          
      - name: bash_new
        type: Bash
        configuration:
          inputResources:
            - name: github_new
            - name: jfrogFEFS_cp
        execution:
          onExecute:
            - echo "executing bash step..."
            - printenv
  
