resources:
  - name: github_new
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
  - name: S_Bash_0219_vmCluster
    type: VmCluster
    configuration:
      sshKey: BSR_SSHKeys
      targets:
        - 1.2.3.4
  - name: jfrogFEFS_cp
    type: FileSpec
    configuration:
      sourceArtifactory: entArt
      pattern: "libs-releases-local/com/jfrog/platform/jfrog-frontend-bin/*/jfrog-frontend-bin-*-*"
      exclusions:
        - "libs-releases-local/com/jfrog/platform/jfrog-frontend-bin/*/jfrog-frontend-bin-*-*.pom"
      recursive: false
      limit: 4
      sortBy:
        - "created"
      sortOrder: "desc"
  - name: S_Bash_0082_Aql
    type: Aql
    configuration:
      sourceArtifactory: s_artifactory
      query: items.find({"@build.name":{"$eq":"artifactory"}})
      addedProperties:
        key1: value1
        key2: value2
      mappings:
        - name: mapping1
          input: "/jfrog-\"fronten\"d-bin/1.*/ jfrog-frontend-bin-1.*-*."
          output: test1
        - name: mapping2
          input: IN
          output: test2

pipelines:
  - name: pipeline_new
    steps:          
      - name: bash_new
        type: Bash
        configuration:
          inputResources:
#             - name: github_new
            - name: jfrogFEFS_cp
#             - name: S_Bash_0082_Aql
#             - name: S_Bash_0219_vmCluster
        execution:
          onExecute:
            - echo "executing bash step..."
            - printenv
            - rm -rf ../frontend && mkdir -p ../frontend/lib
            - pushd $res_jfrogFEFS_cp_resourcePath/com/jfrog/platform/jfrog-frontend-bin
            - jfrogFEVersion=$(find . -mindepth 1 -maxdepth 1 -type d)
            - popd
            - jfrogFEVersion=${jfrogFEVersion//.\/}
            - echo $jfrogFEVersion
#             - jq --arg value0 "$jfrogFEVersion" '. | .frontendVersion=$value0' <<<'{}' > ../frontend/lib/manifest.json
            - tar zxvf $res_jfrogFEFS_cp_resourcePath/com/jfrog/platform/jfrog-frontend-bin/$jfrogFEVersion/jfrog-frontend-bin-$jfrogFEVersion-manifest.tar.gz -C ../frontend/lib/
            - mv ../frontend/lib/frontend/manifest.json ../frontend/lib/manifest.json
            - rm -rf ../frontend/lib/frontend
            - cp -vr $res_jfrogFEFS_cp_resourcePath/com/jfrog/platform/jfrog-frontend-bin/$jfrogFEVersion/jfrog-frontend-bin-$jfrogFEVersion-darwin.tar.gz ../frontend/lib/$jfrogFEVersion-darwin.tar.gz
            - cp -vr $res_jfrogFEFS_cp_resourcePath/com/jfrog/platform/jfrog-frontend-bin/$jfrogFEVersion/jfrog-frontend-bin-$jfrogFEVersion-linux.tar.gz ../frontend/lib/$jfrogFEVersion-linux.tar.gz
            - cp -vr $res_jfrogFEFS_cp_resourcePath/com/jfrog/platform/jfrog-frontend-bin/$jfrogFEVersion/jfrog-frontend-bin-$jfrogFEVersion-windows.zip ../frontend/lib/$jfrogFEVersion-windows.zip
            - pushd ../frontend/lib
            - ls
            - popd
  
