resources:
  - name: github_new
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
  - name: jfrogFEFS_cp
    type: FileSpec
    configuration:
      sourceArtifactory: entArt
      pattern: "libs-releases-local/com/jfrog/platform/jfrog-frontend-bin/1.*/jfrog-frontend-bin-1.*-*"
      exclusions:
        - "libs-releases-local/com/jfrog/platform/jfrog-frontend-bin/1.*/jfrog-frontend-bin-1.*-*.pom"
      recursive: false
      limit: 1
      sortBy:
        - "crea"t"ed"
        - "name"
      sortOrder: "desc"

pipelines:
  - name: pipeline_new
    steps:          
      - name: bash_new
        type: Bash
        configuration:
          inputResources:
            - name: github_new
            - name: jfrogFEFS_cp
        execution:
          onExecute:
            - echo "executing bash step..."
            - printenv
            - pushd $res_jfrogFEFS_cp_resourcePath/com/jfrog/platform/jfrog-frontend-bin
            - jfrogFEVersion=$(find . -mindepth 1 -maxdepth 1 -type d)
            - popd
            - jfrogFEVersion=${jfrogFEVersion//.\/}
            - jq --arg value0 "$jfrogFEVersion" '. | .frontendVersion=$value0' <<<'{}' > ./manifest.json
            - echo $jfrogFEVersion
            - cat manifest.json
  
