resources:
  - name: github_new
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub

pipelines:
  - name: pipeline_new
    steps:          
      - name: bash_new
        type: Bash
        configuration:
          inputResources:
            - name: github_new
        execution:
          onExecute:
            - echo "executing bash step..."
  
