resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub

pipelines:
  - name: bash_pipeline
    steps:
      - name: testBash
        type: Bash
        configuration:
          inputResources:
            - name: gitRepo
        execution:
          onExecute:
            - echo "Executing testBash.."
