resources:
  - name: myRepo
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$
  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          outputResources:
            - name: propertyBag
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
  - name: demo_monorepo
    steps:    
      - name: demoBash_monorepo
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
            - name: propertyBag
        execution:
          onExecute:
            - echo "Executing demoBash_monorepo"
            - printenv
            - echo "missing commit"
            - echo "missing commit"
            
