resources:
  - name: gitRepo_gcp
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub

pipelines:
  - name: gcp_bash_pipeline
    steps:
      - name: testBash_gcp
        type: Bash
        configuration:
          nodePool: gcp
          inputResources:
            - name: gitRepo_gcp
        execution:
          onExecute:
            - docker images        
            - df -h
            - echo "Executing testBash_gcp step"
