resources:
  - name: script_1
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub

pipelines:
  - name: demo_triggeredBy
    steps:
      - name: demoBash
        type: Bash
        configuration:
          inputResources:
            - name: script_1
        execution:
          onExecute:
            - echo "Executing demoBash"
            
