resources:
  - name: docker_build_repo
    type: GitRepo
    configuration:
      path: deepikasl/dockerbuild
      gitProvider: deepikaGithub
      
  - name: docker_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildNumber: 1
      buildName: dockertest  
      
  - name: unsigned_release_bundle_docker_build
    type: ReleaseBundle
    configuration:
      sourceDistribution: demoDist
      name: test-docker-local
      version: v1.0
      
  - name: signed_release_bundle_docker_build
    type: ReleaseBundle
    configuration:
      sourceDistribution: demoDist
      name: test-docker-local
      version: v1.0

  - name: distribution_rule_docker_build
    type: DistributionRule
    configuration:
      sourceDistribution: demoDist
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - "CN"
        - "GB"

pipelines: 
  - name: demo_docker
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: '34.74.146.128:8082/docker-stage-local/deepika'
          dockerImageTag: ${run_number}
          integrations:
            - name: demoArt
          inputResources:
            - name: docker_build_repo    
   
      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: test-docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build
            
      - name: docker_publish
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: docker_build_info  
            
      - name: bundle_docker
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: test-docker-local
          releaseBundleVersion: v0.1.$run_number
          dryRun: false
          sign: false
          description: "docker build"
          inputResources:
            - name: docker_build_info
          outputResources:
            - name: unsigned_release_bundle_docker_build
          releaseNotes:
            syntax: markdown
            content: |
              ## This is a demo to test Docker Build 
                * Build -> Push -> Publish -> Bundle -> Sign -> Distribute
                * Points       
                 
      - name: sign_release_bundle_docker
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: unsigned_release_bundle_docker_build
          outputResources:
            - name: signed_release_bundle_docker_build
            
      - name: dockerDistribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_release_bundle_docker_build
            - name: distribution_rule_docker_build
          integrations: 
            - name: demoDist             
