resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub

pipelines:
  - name: bash_pipeline
    steps:
      - name: testBash
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              custom:
                name: shippabledocker/jfreq
                tag: latest
        execution:
          onExecute:
            - echo "Executing testBash.."
            - add_pipeline_variables pipelineId=$pipeline_id
            - add_run_variables runId=$run_number	
            - echo "state=$run_number" > cache.txt
            - add_cache_files cache.txt pipeline_state_cache
      - name: restoreBash
        type: Bash
        configuration:
          runtime:            
            type: image
            image:
              custom:
                name: shippabledocker/jfreq
                tag: latest
        execution:
          onExecute:
            - echo "Executing restoreBash.."
            - restore_cache_files pipeline_state_cache cache.txt
            - cat cache.txt
