resources:
  - name: gitRepo_cache
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub

pipelines:
  - name: bash_pipeline_cache
    steps:
      - name: testBash_cache
        type: Bash
        configuration:
          nodePool: c07
          inputResources:
            - name: gitRepo_cache
#           runtime:            
#             type: image
#             image:
#               auto:
#                 language: node
#                 versions:
#                   - "10.16.3"
        execution:
          onExecute:
            - echo "Executing testBash.."
