resources:
  - name: gcp_packer
    type: GitRepo
    configuration:
      path: deepikasl/packer-gcp
      gitProvider: deepikaGithub

pipelines:
  - name: bash_pipeline
    steps:
      - name: gcp
        type: Bash
        configuration:
          inputResources:
            - name: gcp_packer
          integrations:
            - name: gcp
        execution:
          onExecute:
            - echo "Executing testBash.."
            - printenv
            - pushd $res_gcp_packer_resourcePath
            - echo $int_gcp_jsonKey > account.json
            - rm -rf /tmp/packer && mkdir -p /tmp/packer
            - PK_FILE="packer_1.4.5_linux_amd64.zip"
            - wget -nv https://releases.hashicorp.com/packer/1.4.5/$PK_FILE
            - unzip -o $PK_FILE -d /tmp/packer
            - sudo chmod +x /tmp/packer/packer
            - mv /tmp/packer/packer /usr/bin/packer
            - ./basePack.sh pipelines-cloud-stg n1-standard-1 ubuntu-1604-lts us-west1 us-west1-b root account.json test-image-family-u16 u16-poc-deepika u16-Image
            - popd
            
