resources:
  - name: gitRepo_1
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
  - name: gitRepo_2
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub

pipelines:
  - name: pipe_1
    steps:
      - name: step_1_1
        type: Bash
        configuration:
          inputResources:
            - name: gitRepo_1
        execution:
          onExecute:
            - echo "pipe_1 -> step_1_1"
      - name: step_1_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1_1
        execution:
          onExecute:
            - echo "pipe_2 -> step_1_2"
  - name: pipe_2
    steps:
      - name: step_2_1
        type: Bash
        configuration:
          inputResources:
            - name: gitRepo_1
        execution:
          onExecute:
            - echo "pipe_1 -> step_2_1"
      - name: step_2_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_2_1
        execution:
          onExecute:
            - echo "pipe_2 -> step_2_2"
    
 
