resources:
  - name: myRepo
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: demo_monorepo
    steps:
      - name: demoBash_monorepo
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
        execution:
          onExecute:
            - echo "Executing demoBash_monorepo"
            - printenv
            - echo "before1"
            - echo "hello"
            - echo "test"
            
            
