resources:
  - name: gcp_packer
    type: GitRepo
    configuration:
      path: deepikasl/packer-gcp
      gitProvider: deepikaGithub

pipelines:
  - name: bash_pipeline
    steps:
      - name: gcp
        type: Bash
        configuration:
          inputResources:
            - name: gcp_packer
          integrations:
            - name: gcp
        execution:
          onExecute:
            - echo "Executing testBash.."
            - printenv
            - pushd $res_gcp_packer_resourcePath
            - touch vars.json
            - replace_envs $int_gcp_jsonKey vars.json
            - cat vars.json
            - popd
            
