resources:
  - name: script_gh
    type: GitRepo
    configuration:
      path: RjSH1/sample-script
      gitProvider: myGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
      
  - name: simple_jenkins_demo
    steps:
      - name: jenkins
        type: Jenkins
        configuration:
          inputResources:
            - name: script_gh
          jenkinsJobName: testPipeline
          integrations:
            - name: myJenkins
      
      - name: step_A
        type: Bash
        configuration:
          inputSteps:
            - name: jenkins
              status:
                - failure
                - error
                - timeout
        execution:
          onExecute:
            - echo "Executing step_A"
            - if [ $step_jenkins_statusName == "failure" ]; then  echo "Do something"; fi
            - if [ $step_jenkins_statusName == "error" ]; then  echo "Do something else"; fi
     
      - name: simple_conditional_B
        type: Bash
        configuration:
          inputSteps:
            - name: jenkins
              status:
                - failure
                - error
        execution:
          onExecute:
            - echo "Executing simple_conditional_B"
            - printenv
