resources:
  - name: script_conditional
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: demo_conditional
    steps:
      - name: demoBash_conditional_A
        type: Bash
        configuration:
          inputResources:
            - name: script_conditional
        execution:
          onExecute:
            - echo "Executing demoBash"
            - printenv
            - blah
     
      - name: demoBash_conditional_B
        type: Bash
        configuration:
          inputSteps:
            - name: demoBash_conditional_A
              status:
                - failure
        execution:
          onExecute:
            - echo "Executing demoBash_conditional_B"
            - printenv
            
