resources:
  - name: artifactory_go_example
    type: GitRepo
    configuration:
      path: deepikasl/artifactory-go-example
      gitProvider: deepikaGithub
  - name: go_build_info_publish
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: go_example_build_publish
      buildNumber: 1
  - name: promoted_go_build_info_go_publish
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: promote_go_build_publish
      buildNumber: 1


pipelines:
  - name: go_publish_example
    steps:
      - name: publish_go
        type: GoPublishModule
        configuration:
          nodePool: aws-demo-pool
          sourceLocation: .
          version: v1.2.1
          targetRepository: deepika-go
          deps: all
          inputResources:
            - name: artifactory_go_example
          integrations:
            - name: art
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          nodePool: aws-demo-pool
          inputSteps:
            - name: publish_go
          outputResources:
            - name: go_build_info_publish
      - name: promote_build_go
        type: PromoteBuild
        configuration:
          nodePool: aws-demo-pool
          targetRepository: deepika-go-promote
          comment: "comment"
          status: "ready"
          copy: true
          includeDependencies: true
          integrations:
            - name: art
          inputResources:
            - name: go_build_info_publish
          outputResources:
            - name: promoted_go_build_info_go_publish
