resources:
  - name: script_conditional
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: demo_run
    steps:
      - name: step_AA
        type: Bash
        configuration:
          inputResources:
            - name: script_conditional
        execution:
          onExecute:
            - echo "Executing step_B"
            - printenv
      - name: step_BB
        type: Bash
        configuration:
          inputSteps:
            - name: step_AA
        execution:
          onExecute:
            - echo "Executing step_B"
            - printenv
      - name: step_CC
        type: Bash
#         configuration:
        execution:
          onExecute:
            - echo "Executing step_CC"
            - printenv
     
      - name: conditional_DD
        type: Bash
        configuration:
          inputSteps:
            - name: step_BB
              status:
                - success
            - name: step_CC
              status:
                - failure
                - skipped
                - cancelled
        execution:
          onExecute:
            - echo "Executing conditional_DD"
            - printenv
  - name: demo_conditional
    steps:
      - name: step_A
        type: Bash
        configuration:
          inputResources:
            - name: script_conditional
        execution:
          onExecute:
            - echo "Executing step_A"
            - printenv
     
      - name: step_B
        type: Bash
        configuration:
          inputSteps:
            - name: step_A
        execution:
          onExecute:
            - echo "Executing step_B"
            - printenv
      - name: step_C
        type: Bash
        configuration:
          inputSteps:
            - name: step_A
        execution:
          onExecute:
            - echo "Executing step_C"
            - printenv
      - name: conditional_D
        type: Bash
        configuration:
          inputSteps:
            - name: step_B
              status:
                - success
            - name: step_C
              status:
                - failure
                - skipped
                - cancelled
        execution:
          onExecute:
            - echo "Executing conditional_D"
            - printenv
            
