resources:
  - name: gitRepo
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub

pipelines:
  - name: bash_pipeline
    steps:
      - name: testBash
        type: Bash
        configuration:
          runtime:            
            type: image
              custom:
                name: shippabledocker/jfreq
                tag: latest
        execution:
          onExecute:
            - echo "Executing testBash.."
            - add_pipeline_variables pipelineId=$pipeline_id
            - add_pipeline_variables test='test'	        
            - add_run_variables runId=$run_number	
            - add_run_variables testId=$step_id	
